### ISSUE TITLE
A quick question about CSS Bootstrap usage 

### ISSUE THREAD

**Issue by BoQsc** [TZMCommunity/materials#5]
![image](https://user-images.githubusercontent.com/21064622/100539245-d30a6600-323d-11eb-9917-160a194203d3.png)

Modifying a website that is hooked with Bootstrap CSS framework **is no easier than using a pure CSS3.** 
I don't want to be rude, but: **CSS frameworks are technologically obsolete.**  
<code>Would it not be better to simply use **CSS directly** **without frameworks** like Bootstrap. </code>

No need to answer with full paragraphs: **just yes or no and maybe some few more words.**

## A suggestion for the future
Right now I have a **temporal** rage drive to reverse engineer current TZM Community website layout **away from Bootstrap**  
and it will be gone before this issue gets the attention.

I get this "productive" focused "rage" once or twice a year, sometimes might not be even that,    
So I might visit this issue next time and actually propose something about it, or (and) do more in depth analysis,  
maybe a proper explanation and documentation.  
* **That might include Jekyll itself** usage and its problems
*  **Bootstrap framework** usage problems

**Comment by BoQsc** [comment]
This issue is more of a personal note.  **Github simply does not support making an issue private.**

**Comment by BoQsc** [comment]
I'm not sure how https://forestry.io/ 
works right now. But if the design is from forestry.io then it would be not possible to move away from Bootstrap framework.  
Since the hassle of integration would be too much.   

If that's the case, then the last available thing would be:   
to start learning Bootstrap in depth and tweaking the current TZM Community pages design.

**Comment by jeukku** [comment]
I haven't had any problems with Bootstrap but we are currently looking into re-creating the tzm.community template with something else than Jekyll so I wouldn't put much effort to this current one. Especially not the "matrials" site. Possibly we will be using Hugo.

**Comment by BoQsc** [comment]
As a side note for https://forestry.io/   
Forestry.io offers are garbage. But I have no alternatives to suggest.
The prices between **Personal** and **Starter** are skyrocketing-like.
And this nonsensical deal of `Sites frozen after 3 months of inactivity (no edit)` technically should not even exist.
![image](https://user-images.githubusercontent.com/21064622/100540321-58dddf80-3245-11eb-9530-ff6907b319f4.png)

**Comment by jeukku** [comment]
Forestry.io is just one way to edit the pages. Everyone can use Personal accounts, but it would be good to have other options.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
